version: '2'
services:
    testhipster-app:
        image: testhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testhipster-mysql:3306/testhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testhipster-mysql:
        extends:
            file: mysql.yml
            service: testhipster-mysql
